---
title: "linear_models"
author: "Ruoxi Li"
date: "`r Sys.Date()`"
output: github_document
---

```{r}
library(tidyverse)
library(p8105.datasets)
set.seed(1)
library(broom)
```

```{r}
data("nyc_airbnb")
nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, neighborhood, room_type)
```

Let's fit a model!


```{r}
fit = lm(price~stars+borough,data=nyc_airbnb)
summary(fit)
summary(fit)$coef
```

tidy up the output instead

```{r}
fit |>
  broom::glance()
```

tidy up the coefficients

```{r}
fit|>
  broom::tidy() |>
#a tibble
  mutate(term = str_replace(term,"^borough","Borough:"))|>
  knitr::kable(digits=3)
```

```{r}
fit = 
  nyc_airbnb |>
  mutate(
    borough = fct_infreq(borough),
    room_type=fct_infreq(room_type)
  )|>
  lm(price~stars+borough+room_type,data= _)
fit|>
  broom::tidy()
```

## Quick look at diagnostics

```{r}
nyc_airbnb |>
  modelr::add_residuals(fit)|>
  #ggplot(aes(x=resid)) +
  # geom_density()+
  # xlim(-100,500)
  ggplot(aes(x=stars,y=resid))+
  geom_point()

nyc_airbnb |>
  modelr::add_residuals(fit)|>
   ggplot(aes(x = borough, y = resid)) + geom_violin()
```



## Hypothesis test for categorical predictor

fit a null and alternative
```{r}
fit_null = lm(price~stars+borough,data=nyc_airbnb) 
fit_alternative = lm(price~stars+borough+room_type,data=nyc_airbnb) 
anova(fit_null,fit_alternative)|>
  broom::tidy()
```

## Borough-level difference 

```{r}
fit = 
  nyc_airbnb |>
  lm(price = stars*borough +room_type*borough ,data = _)
fit |>
  broom::tidy()
```

```{r}

airbnb_lm =function(df){
  lm(price~stars +room_type,data=df)
}
nyc_airbnb |>
  nest(df = -borough) |>
  mutate(
    models = map(df,airbnb_lm),
    results = map(models,broom::tidy)
  )|>
  select(borough,results)|>
  unnest(results)|>
  select(borough,term,estimate)|>
  pivot_wider(
    names_from = term,
    values_from = estimate
  ) |>
  knitr::kable(digits=2)
```

same thing but just a little different

```{r}
nyc_airbnb |>
  nest(df = -borough) |>
  mutate(
    models = map(df,\(df) lm(price~stars +room_type,data=df)),
    results = map(models,broom::tidy)
  )|>
  select(borough,results)|>
  unnest(results)|>
  select(borough,term,estimate)|>
  pivot_wider(
    names_from = term,
    values_from = estimate
  ) |>
  knitr::kable(digits=2)
```

## Homicide

```{r}
baltimore_df = 
  read_csv("homicide-data.csv") |>
    filter(city == "Baltimore") |> 
  mutate(
    resolved = as.numeric(disposition == "Closed by arrest"),
    victim_age = as.numeric(victim_age),
    victim_race = fct_relevel(victim_race, "White")) |> 
  select(resolved, victim_age, victim_race, victim_sex)
```

fitting a logistic regression

```{r}
fit_logistic =
  baltimore_df |>
  glm(
    resolved ~ victim_age +victim_race+victim_sex,
    data = _,
    family = binomial()
  )
```

```{r}
fit_logistic |> 
  broom::tidy() |> 
  mutate(OR = exp(estimate)) |>
  select(term, log_OR = estimate, OR, p.value) |> 
  knitr::kable(digits = 3)
```